name: cd

on:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create tag
        id: commit_hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Compile app
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux go build -o build/app cmd/main.go

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/vaynerakawalo/${{ github.event.repository.name }}:${{ steps.commit_hash.outputs.SHORT_SHA }}
            ghcr.io/vaynerakawalo/${{ github.event.repository.name }}:latest
